PhotoService/PhotoService/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings           # 追加
from django.conf.urls.static import static # 追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

# MEDIA_ROOT を公開する(アクセス可能にする) 
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT) # 追加

PhotoService/app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('users/<int:pk>/', views.users_detail, name='users_detail'),
    path('photos/<int:pk>/', views.photos_detail, name='photos_detail'),
    path('photos/new/', views.photos_new, name='photos_new'),
    path('photos/<int:pk>/delete/', views.photos_delete,
                      name='photos_delete'),
    path('photos/<str:category>/', views.photos_category,
                      name='photos_category'),
    path('signup/', views.signup, name='signup'),
    path('login/',
         auth_views.LoginView.as_view(template_name='app/login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

PhotoService/app/models.py
from django.db import models
from django.contrib.auth.models import User

# Category モデルを作成
class Category(models.Model):
    title = models.CharField(max_length=20)
    def __str__(self):
       return self.title

class Photo(models.Model):
    title = models.CharField(max_length=150)
    comment = models.TextField(blank=True)
    image = models.ImageField(upload_to='photos')
    category = models.ForeignKey(Category,
                                 on_delete=models.PROTECT) # 追加 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

PhotoService/app/forms.py
from django.forms import ModelForm
from .models import Photo

class PhotoForm(ModelForm):
    class Meta:
       model = Photo
       fields = ['title', 'comment', 'image', 'category']

PhotoService/app/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.models import User
from .models import Photo
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .forms import PhotoForm
from django.contrib import messages
from django.views.decorators.http import require_POST
from .models import Photo, Category

def photos_detail(request, pk):
  photo = get_object_or_404(Photo, pk=pk)
  return render(request, 'app/photos_detail.html', {'photo': photo})

@require_POST
def photos_delete(request, pk):
  photo = get_object_or_404(Photo, pk=pk)
  photo.delete()
  return redirect('app:users_detail', request.user.id)

@login_required
def photos_new(request):
 if request.method == "POST":
  form = PhotoForm(request.POST, request.FILES)
  if form.is_valid():
     photo = form.save(commit=False)
     photo.user = request.user
     photo.save()
     messages.success(request, "投稿が完了しました!")
  return redirect('app:users_detail', pk=request.user.pk)
 else:
  form = PhotoForm()
 return render(request, 'app/photos_new.html', {'form': form})

def signup(request):
 form = UserCreationForm()
 return render(request, 'app/signup.html', {'form': form})


def index(request):
 photos = Photo.objects.all().order_by('-created_at')
 return render(request, 'app/index.html', {'photos': photos})


def users_detail(request, pk):
 user = get_object_or_404(User, pk=pk)
 photos = user.photo_set.all().order_by('-created_at')
 return render(request, 'app/users_detail.html', {'user': user,'photos': photos})


def signup(request):
 if request.method == 'POST':
  form = UserCreationForm(request.POST)
  if form.is_valid():
   new_user = form.save()  # ユーザーインスタンスを保存
   input_username = form.cleaned_data['username']
   input_password = form.cleaned_data['password1']
      # フォームの入力値で認証できればユーザーオブジェクト、できなければNone を返す

   new_user = authenticate(username=input_username,
         password=input_password)

      # 認証成功時のみ、ユーザーをログインさせる
   if new_user is not None:
    login(request, new_user)
    return redirect('app:users_detail', pk=new_user.pk)
 else:
  form = UserCreationForm()
  return render(request, 'app/signup.html', {'form': form})

def photos_category(request, category):
 # title が URL の文字列と一致する Category インスタンスを取得
 category = Category.objects.get(title=category)
 # 取得した Category に属する Photo 一覧を取得
 photos = Photo.objects.filter(category=category).order_by('-created_at')

 return render(request, 'app/index.html', {'photos': photos,'category':category})

PhotoService/app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<title>写真投稿サイト</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	</head>
	<body>
		<header>
			<div class="container">
					<h1><a href="{% url 'app:index' %}">写真投稿サイト</a></h1> 
					<div class="header-menu">
						<a href="{% url 'app:photos_new' %}">投稿</a>  
						{% if request.user.is_authenticated %}
							<a href="{% url 'app:users_detail' request.user.id %}">マイページ </a>
							<a href="{% url 'app:logout' %}">ログアウト</a> 
						{% else %}
							<a href="{% url 'app:login' %}">ログイン</a> 
						{% endif %}
					</div>
			</div>
		</header>
		<div class="container">
			{% for message in messages %}
			   <p class="message-success">{{ message }}</p>
			{% endfor %}
			{% block content %}{% endblock %}
		</div>
	</body>
</html>

PhotoService/app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}

{% if category %}
	<h2>カテゴリー:{{ category.title }} の検索結果</h2>
{% endif %}

{% include 'app/photos_list.html' %}

{% endblock %}

PhotoService/app/templates/app/login.html
{% extends 'app/base.html' %}

{% block content %}

<form class="form-signin" method="post">{% csrf_token %}
    {% if form.errors %}
			<p>ユーザー名かパスワードが間違っています。</p> 
		{% endif %}
		<h2>ログイン</h2> 
		<label>ユーザー名</label>
		<input name="username">
		<br>
		<label>パスワード</label>
		<input type="password" name="password"> 
		<br>
		<input type="submit" value="ログイン">
</form>

{% endblock %}

PhotoService/app/templates/app/photos_detail.html
{% extends 'app/base.html' %}

{% block content %}

<div class="photo-detail">
<img src="{{ photo.image.url }}" class="photo-img">
<div class="photo-info">
    <a href="{% url 'app:users_detail'
                      photo.user.id %}">@{{ photo.user }}</a>
</div>

<h2>{{ photo.title }}</h2>
<p>{{ photo.comment }}</p>

<!-- 削除ボタン -->
{% if request.user == photo.user %}
<form method="post" action="{% url 'app:photos_delete' photo.id %}">{%csrf_token %}
	<button class="btn" type="submit" onclick='return confirm("本当に削除しますか?");'>削除</button>
</form>
{% endif %}

</div>

{% endblock %}

PhotoService/app/templates/app/photos_list.html
<div class="photo-container">
    {% for photo in photos %}
        <div class="photo">
           <a href="{% url 'app:photos_detail' photo.id %}">
               <img src="{{ photo.image.url }}" class="photo-img">
           </a>
           <div class="photo-info">
               <a href="{% url 'app:photos_category' category=photo.category %}"
                  class="category">{{ photo.category }}</a>
               <a href="{% url 'app:users_detail' photo.user.id %}">@{{ photo.user }}</a>
           </div>
        </div>
    {% endfor %}
    </div>

PhotoService/app/templates/app/photos_new.html
{% extends 'app/base.html' %}

{% block content %}

<div>
	<a href="{% url 'app:index' %}">ホームに戻る</a>
</div>
<form action="{% url 'app:photos_new' %}" method="POST"
                      enctype="multipart/form-data">{% csrf_token %}

	<table> 
		<tr>
			<th>タイトル</th>
			<td>{{ form.title }}</td>
		</tr>
		<tr>
			<th>コメント</th>
			<td>{{ form.comment }}</td>
		</tr> 
		<tr>
			<th>画像</th>
			<td>{{ form.image }}</td>
		</tr>
		<tr>
			<th>カテゴリー</th>
			<td>{{ form.category }}</td>
		</tr>
	</table>
	<button type="submit" class="btn">保存</button> 
</form>

{% endblock %}

PhotoService/app/templates/app/signup.html
{% extends 'app/base.html' %} 

{% block content %} 

<h2>ユーザー登録</h2>

<form method="post" action="{% url 'app:signup' %}">{% csrf_token %} 
	<label>ユーザー名</label>
	{{ form.username }}
	{{ form.username.errors }}
	<br>
	<label>パスワード</label>
	{{ form.password1 }}
	{{ form.password1.errors }} 
	<br> 
	<label>パスワード(確認)</label>
	{{ form.password2 }}
	{{ form.password2.errors }}
	<br>
	<input type="submit" value="登録する">
</form>

<p><a href="{% url 'app:login' %}">ログインはこちら</a></p> 
{% endblock %}

PhotoService/app/templates/app/users_detail.html
{% extends 'app/base.html' %}

{% block content %}

<h2 class="user-name">@{{ user.username }}</h2>

{% if photos.count != 0 %}
	<p>投稿<strong>{{ photos.count }}</strong>件</p>
{% else %}
		{% if user == request.user %}
			<p>初めての投稿をしてみましょう!</p> 
		{% else %}
			<p>@{{ user.username }}さんはまだ投稿していません。</p> 
		{% endif %}
{% endif %}

{% include 'app/photos_list.html' %}
{% endblock %}